version: 2.1
jobs:
  deploy:
    docker:
      - image: pionux/build-deploy:0.1
    steps:
      - run:
          name: 'Deploy news'
          command: |
            git clone https://github.com/Densovan/news.git
            cd rithy.org && hugo -D
            cd .. && touch run-build
            echo $build > run-build
            chmod +x run-build && ./run-build
workflows:
  workflow:
    jobs:
      - deploy
