version: 2.1
jobs:
  deploy:
    docker:
      - image: pionux/build-deploy:0.1
    steps:
      - run:
          name: 'Deploy news'
          command: |
            git clone https://github.com/koompi/koompinews.git
            cd koompinews/client
            npm install -g serve
            npm run build
            echo $develop > build-client
            chmod +x build-client && ./build-client
workflows:
  workflow:
    jobs:
      - deploy
