version: 2.1
jobs:
  deploy:
    docker:
      - image: pionux/build-deploy:0.1
    steps:
      - run:
          name: 'Build To Production'
          command: |
            git clone https://github.com/koompi/koompinews.git
            cd koompinews/client
            npm install
            npm install -g serve
            CI=false npm run build
      - run:
          name: 'Deploy To Production'
          command: |
            cd koompinews/client
            echo $develop > build-client
            chmod +x build-client && ./build-client
workflows:
  workflow:
    jobs:
      - deploy
